### ISSUE TITLE
Visualization of evidence used in calculation

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/KSTAR#48]
**Feature request - improve coupling of data used with analysis results**
It would be very helpful to add a visualization of the number of sites used in an experimental column in the process of KSTAR. This would be most helpful when coupled with dotplots of scores (for example, one could know if low activity results from low sensitivity due to to few sites.

**Describe the solution you'd like**
A graph indication (likely on the bottom of the dotplot, but could be at the top too) of the total number of sites used for an individual experiment, relative to the maximum number of sites used in any experiment in a dataset. Could be a circle, or a different shape to avoid confusion with metadata and scores. Perhaps a flag that defaults to plotting on bottom between tick labels and scores or at the top, below any metadata (default bottom makes the most sense to me).

**Describe alternatives you've considered**
Currently, we rely on using the investigation tools to report these numbers, but a direct ability to look at this with scores is preferred.

**Additional context**

**Comment by srcrowl** [comment]
A new function in DotPlot class called evidence_size() has been added for this purpose
