### ISSUE TITLE
Inspection: Would like to know what the evidence is that is related to a kinase activity

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/KSTAR#50]
**Feature: Would like to know something about substrates in networks**
It would be nice to know something for a "biomarker" type analysis -- what substrates in an experiment are giving rise across the set of networks to the information

**Types of information we would like**

- What is the substrate-network information of sites that were observed and the frequency of their inclusion in a network. 
- Maybe statistics about how consistent kinase networks are across networks (e.g. if we are using 50 different networks, what substrates in an experiment are connected to the same kinases consistently? How consistent are kinase networks on that evidence? How do we find how often substrates give rise to other kinases and is that as consistent or not with other kinases?

**Comment by srcrowl** [comment]
- Bullet Point 1 has been added: see the analysis.interactions module
- For second bullet, could be expanded, but there are functions for comparing network size and overlap between kinases in analysis.kinase_MI (based on mutual information of substrates)
